### ISSUE TITLE
sample weights for GMM

### ISSUE THREAD

**Issue by ngoix** [jmschrei/pomegranate#151]
Does `GeneralMixtureModel.fit()` support a weight on the training samples?
It returns no error, but the same result (independently on the weights provided). 
And no error is returned, even when weights has wrong shapes:

```
#code snipet

import numpy as np
from pomegranate import GeneralMixtureModel
from pomegranate import MultivariateGaussianDistribution

X = np.array([[1, 2],[2, 2],[3, 4]])
w = np.zeros((356,))

gmm = GeneralMixtureModel(MultivariateGaussianDistribution, n_components=1)
gmm.fit(X, weights=w)
preds = gmm.predict(X)
print preds

```

return no errors.

**Comment by jmschrei** [comment]
So the API supports it because the first iteration of GMM did support it, but it looks like in a recent revision I actually ignore the weight vector. Whoops, I'll fix that tonight. Thanks for pointing that out.

**Comment by jmschrei** [comment]
#152 should fix this, as well as include a bunch of other GMM goodies (including log_probability calculating the logp for every point, instead of assuming it's a single point, and multithreaded parallelization wrappers for all prediction tasks)

**Comment by ngoix** [comment]
Thank you!

2016-07-25 23:42 GMT-04:00 Jacob Schreiber <notifications@github.com>:

**Comment by ngoix** [comment]
Actually I still have the same problems even with your fix...

**Comment by jmschrei** [comment]
I didn't actually merge the fix yet, as the tests were failing and I had to run to work. I think I've fixed the issue now though-- merge should be imminent

**Comment by ngoix** [comment]
Yes I know I reproduced your changes...

**Comment by ngoix** [comment]
Since the tests were ok with python 2.7

**Comment by jmschrei** [comment]
Can you provide some minimal code with the expected results? That would be helpful for me in isolating the issue

**Comment by jmschrei** [comment]
Okay I've found the issue, figuring it out. Patch should come out tomorrow. I was weighting before normalization, not after, whoops.

**Comment by jmschrei** [comment]
I just pushed a fix for this. I was not calculating the weighted log probability properly, but now I am! Please give it a try and let me know if it works for you.

**Comment by ngoix** [comment]
It seems to work!
 However, it raises no error when the shape of `weights` is not `(n_samples,)`.
It just yields e.g. `model.weights = array[-inf, -inf, -inf]` if there is 3 components.
And when the `weights` vector has the same shape as the data `(n_samples, n_features)`, it produces something (with regular model weights). What does the model does in this case?

**Comment by jmschrei** [comment]
Hooray!

So yeah, pomegranate does lack error messages when the user does something inappropriate, mostly because I barely have time to add the features which I need and unit tests, much less rigorous input testing. This is a known problem, and I'll open an issue to make sure I finish it.

In that case, it will use the first n_samples in the pointer array as the weights. It'll go through the rows until n_samples is reached, not down the columns as you'd like. Do you want an ability to have different weights for a point for each component?

**Comment by ngoix** [comment]
Yes seems interesting! But what does it means (according to a model which is not linear) for a point to have different weights for different features? In my case it is kind of measurement error, but I wonder how you can put this into a gaussian model.

**Comment by jmschrei** [comment]
My initial assumption would be that it is a prior distribution on which component you think each sample belongs to (sort of nudging some points to be together even if the observation isn't that close). I don't have any math to back up that intuition though.

**Comment by ngoix** [comment]
For me, one weight per sample make the assumption that the sample is `around the true one' by a circle, ie the point we observe is a realization of a gaussian with diagonal covariance (1 / weight) * Identity and with mean the `true point'. (we can think of `weight' as the squared inverse of a measurement error.)

Allowing different weights per features would generalize this approach to gaussian with full covariance matrix, which would be very useful for my specific problem!

**Comment by jmschrei** [comment]
Are you saying you want each column in the weight matrix to correspond to a ~dimension~ or to a ~component~ in the GMM?

**Comment by ngoix** [comment]
To a dimension.

**Comment by jmschrei** [comment]
As an update on this, I'm still looking to add this, but it will be after my PyData talk next week. A million tiny things need to be done before then!

**Comment by ngoix** [comment]
Ok cool :)

**Comment by jmschrei** [comment]
By "add this after my PyData talk next week" I apparently meant "never get around to it." I'd still be interested in considering a general technique that takes in a (n, d) sized weight matrix instead of just a length n vector. I'm going to close this issue for now, though, as I'll probably take the more general approach for all methods if/when I get to it.
