### ISSUE TITLE
api for hmm multivariable gaussian

### ISSUE THREAD

**Issue by VertexC** [jmschrei/pomegranate#455]
Hi,

I am trying to use the HiddenMarkovModel for Multivariable Gaussian data.

The observation sequence is G by E matrix, where G is for sequence size and E is for data dimension.  I would like to train the model with observation sequence  to get transition and emission matrix. Which is K by K and K by E. Where K is for number of states.

I have looked into the document, and I think the part below is what I want but there is no more specified API reference for that.
```python
from pomegranate import *
model = HiddenMarkovModel.from_samples(NormalDistribution, n_components=K, X=x_m, algorithm='baum-welch')
```
I want to fetch transition and emission (and prior) from trained model and set them as the initialized parameter for the next HMM. After trained, I want to get the predicted state and weight of each state (as how 'baum-welc' does) for a given sequence.

Can you help me on that?
Thanks.

**Comment by jkleckner** [comment]
I don't know why the "read the docs" for latest doesn't include the generated API doc but you can find that function documentation in the source here: https://github.com/jmschrei/pomegranate/blob/master/pomegranate/hmm.pyx#L3425

**Comment by jmschrei** [comment]
The ReadTheDocs page has been fixed to include API documentation. 

If you want to get the trained transition matrix, you can use `model.dense_transition_matrix()` where the rows and columns are ordered according to the states in `model.states`. If you're looking to get the emission matrix, you'll have to pull our each individual distribution using something like `[state.distribution.parameters for state in model.states]`.

**Comment by VertexC** [comment]
Thanks for your replies. But I still get into some problem.
```python
"""
This is the script to try on hmm in pomegranate package
http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html
"""


import numpy as np
# make up data
# preset parameters
E = 3  
G = 5  
K = 4 
# initialize the matrix
x_m = np.asmatrix(np.zeros((E, G)))
def initialize():
    g = 0
    while g < G:
        x_m[:, g] = abs(
            np.matrix(np.random.multivariate_normal((theta_m.T * y_m[:, g]).flatten().tolist()[0], np.eye(E)))).T
        g += 1
if __name__ == '__main__':
    initialize()
    model = HiddenMarkovModel.from_samples(NormalDistribution, n_components=K, X=x_m, algorithm='baum-welch')
    trans_m = model.dense_transition_matrix()
    print(trans_m)
    for state in model.states:
        print(state.distribution)
```
The result shows that
```
trans_m
[[0.25 0.25 0.25 0.25 0.   0.  ]
 [0.25 0.25 0.25 0.25 0.   0.  ]
 [0.25 0.25 0.25 0.25 0.   0.  ]
 [0.25 0.25 0.25 0.25 0.   0.  ]
 [0.25 0.25 0.25 0.25 0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]]

model.states
{
    "class" :"Distribution",
    "name" :"NormalDistribution",
    "parameters" :[
        NaN,
        NaN
    ],
    "frozen" :false
}
{
    "class" :"Distribution",
    "name" :"NormalDistribution",
    "parameters" :[
        NaN,
        NaN
    ],
    "frozen" :false
}
{
    "class" :"Distribution",
    "name" :"NormalDistribution",
    "parameters" :[
        NaN,
        NaN
    ],
    "frozen" :false
}
{
    "class" :"Distribution",
    "name" :"NormalDistribution",
    "parameters" :[
        NaN,
        NaN
    ],
    "frozen" :false
}
None
None
```
I am expecting transition matrix as K by K(4), but it shows as 6 and filled with same number. And the parameter for each state is NaN. It seems that the model is not trained. BTW, are the last two None for start and end state?
THANKS.

**Comment by jkleckner** [comment]
@VertexC   Try copying the transposed array with `).T.copy()` to see if that works.
See the comment here: https://github.com/jmschrei/pomegranate/issues/414#issuecomment-390734369

**Comment by VertexC** [comment]
Thanks for the reference! I solve the issue by enlarge the observation data set.

**Comment by jmschrei** [comment]
Great. :) Let us know if you have any other questions. You can also smooth your data set by adding in pseudocounts, if you encounter trouble in the future.

**Comment by VertexC** [comment]
Hi @jmschrei , the "model not trained problem" occurs again when I apply it to my research project. 
Here is a test script, where you can get not trained parameters and by running it several times. Is there any way to get at least trained result? 

```python
"""
the HMM model used for this project
currently built on pomegranate package
http://pomegranate.readthedocs.io/en/latest/HiddenMarkovModel.html
"""
import os
import sys
is_exp_script = True
script_dir = os.path.split(os.path.realpath(__file__))[0]
import util.utility as util
import util.myconfig as myconfig
if is_exp_script:
    root_path = os.path.join(script_dir, "../../../")
else:
    root_path = os.path.join(script_dir, "../../")
configs = myconfig.config(root_path, log_dir=script_dir, data_type="p")

import sys
from pomegranate import *
import numpy as np

class hmm(object):
    def __init__(self):
        pass
    
    def from_matrix(self, trans_m, params, start_m):
        """
        :param trans_m: The transmation matrix
        :param params: The list [[mu,sigma]] 
        :return :
        """
        distributions = [NormalDistribution(element[0], element[1]) for element in params]
        self.model = HiddenMarkovModel.from_matrix(trans_m, distributions, start_m)

    def from_samples(self, sequence, K):
        """
        :param sequence: An array of some sort (list, numpy.ndarray, tuple..) of sequences, 
                where each sequence is a numpy array, 
                which is 1 dimensional if the HMM is a one dimensional array, 
                or multidimensional if the HMM supports multiple dimensions.
                note: if sequance is G by E, then G should be the length of the sequence, E for dimential of single state.
        :param componets: Number of states
        :return :
        """
        self.model = HiddenMarkovModel.from_samples(NormalDistribution, n_components=K, X=sequence.copy(), algorithm='baum-welch')

    def get_state_count(self):
        """
        :return: The number of states in the model. The actual state plus 2(start and end states)
        """
        return self.model.state_count()

    def get_params(self):
        """
        :return: The list [[mu,sigma]] 
                where the mean (mu) and the standard deviation (sigma) of distribution for each state.
                note: using NormalDistribution as default. See http://pomegranate.readthedocs.io/en/latest/Distributions.html for more detailed information.
        """
        K = self.get_state_count() - 2
        params = [self.model.states[k].distribution.parameters for k in range(K)]
        return params
    
    def get_trans_m(self):
        """
        :return: The transition matrix, filled with the probabilities of each state transitioning to each other state.
        """
        return self.model.dense_transition_matrix()[:self.model.silent_start, :self.model.silent_start]

    def get_start_m(self):
        """
        :return: The probabilities of starting in each of the states.
        """
        start_m = self.model.dense_transition_matrix()[self.model.start_index, :self.model.silent_start]  
        return start_m

    def predict(self, sequence):
        """
        :param sequence: An array of some sort (list, numpy.ndarray, tuple..) of sequences, 
                  where each sequence is a numpy array, 
                  which is 1 dimensional if the HMM is a one dimensional array, 
                  or multidimensional if the HMM supports multiple dimensions.
                  note: if sequance is G by E, then G should be the length of the sequence, E for dimential of single state.
        :return: The predicted path using viterbi, the hidden start state is stripped.
        """
        result = self.model.predict(sequence.copy(), algorithm="viterbi")[1:]
        return result

    def predict_log_proba(self, sequence):
        """
        :param sequence: An array of some sort (list, numpy.ndarray, tuple..) of sequences, 
                  where each sequence is a numpy array, 
                  which is 1 dimensional if the HMM is a one dimensional array, 
                  or multidimensional if the HMM supports multiple dimensions.
                  note: if sequance is G by E, then G should be the length of the sequence, E for dimential of single state.
        :return: The log normalized probabilities of each state generating each emission.
        """
        result = self.model.predict_log_proba(sequence.copy())
        return result

    def predict_proba(self, sequence):
        """
        :param sequence: An array of some sort (list, numpy.ndarray, tuple..) of sequences, 
                  where each sequence is a numpy array, 
                  which is 1 dimensional if the HMM is a one dimensional array, 
                  or multidimensional if the HMM supports multiple dimensions.
                  note: if sequance is G by E, then G should be the length of the sequence, E for dimential of single state.
        :return: The normalized probabilities of each state generating each emission.
        """
        result = self.model.predict_proba(sequence.copy())
        return result 

def hmm_test():
    # make up data
    x_m = np.asarray(util.read_matrix(os.path.join(script_dir, "data.txt")))
    # x_m is 5 by 100
    model = hmm()
    model.from_samples(x_m.T, K)
    start_m = model.get_start_m()
    K_p = model.get_state_count()
    trans_m = model.get_trans_m()
    params = model.get_params()
    print("======start_m========")
    print(start_m)
    print("======trans_m========")
    print(trans_m)
    print("======params========")
    print(params)

    # test_model = hmm()
    # test_model.from_matrix(trans_m, params, start_m)
    # log_pro = test_model.predict_log_proba(x_m.T)
    # pro = test_model.predict_proba(x_m.T)
    # path = test_model.predict(x_m.T)
    # print(log_pro)
    # print(pro)
    # print(path)

def main():
    hmm_test()
    return 0

if __name__ == "__main__":
    sys.exit(main())
```

**Comment by VertexC** [comment]
# data.txt
5 100
0.11378905 0.1360566 0.0909606 0.09800835 0.15231 0.1019028 0.22650114999999998 0.1449376 0.12076025000000001 0.0188559 0.15037795 0.11875714999999999 0.23774890000000004 0.25594 0.5707108000000001 0.5278589 0.20828680000000002 0.24033925 0.4605431999999999 0.22473849999999998 0.25594 0.20715219999999998 0.2553727 0.494941 0.3765786 0.48583619999999994 0.17240935000000002 0.2589243 0.25594 0.25594 0.250267 0.16839759999999998 0.17272345 0.08899594999999999 0.08799154999999999 0.43411149999999993 0.2541256 0.25594 0.3469880000000001 0.25594 0.20658490000000002 0.25594 0.25594 0.2542381 0.10737624999999999 0.28121435 0.73400835 0.6861769 0.27747605000000003 0.08906375000000001 0.26604819999999996 0.047167999999999995 0.17684745 0.21851284999999998 0.32960625 0.100744 0.17875554999999999 0.1253596 0.2604924 0.45852180000000003 0.27507754999999995 0.23069515000000002 0.24544495000000002 0.11418384999999999 0.22615675 0.5364444 0.2753752 0.23353164999999998 0.20800315000000003 0.3623363 0.2230366 0.23409895 0.22842595000000002 0.2500936 0.14287329999999998 0.13050475 0.21219234999999997 0.23706204999999997 0.22445484999999998 0.23182975 0.22631849999999998 0.5410797 0.1526178 0.0863893 0.07635054999999999 0.20394895 0.2833099 0.2525362 0.2534977 0.24150219999999997 0.176767 0.047400950000000004 0.31910784999999997 0.2060003 0.3307587 0.248335 0.22239085 0.23551249999999999 0.23578 0.22795605000000002 
0.08228509999999999 0.10494674999999999 0.062132700000000006 0.0685236 0.11907 0.0818976 0.1835622 0.11293840000000001 0.08578865000000001 0.0113252 0.09551970000000001 0.257406 0.2058248 0.520777 0.21273 0.2113104 0.20035920000000002 0.20799800000000002 0.19036675 0.20428000000000002 0.21273 0.2000888 0.21158079999999999 0.21273 0.21273 0.21273 0.14844464999999998 0.17162799999999998 0.21273 0.21273 0.210364 0.1425461 0.13724605 0.06587615 0.06017614999999999 0.19421 0.21106319999999998 0.21273 0.21273 0.5112179 0.31894075 0.21273 0.32203699999999996 0.642414 0.2082029 0.6621938 0.2039368 0.54006425 0.48124575 0.074129 0.17205575 0.04722485 0.14097735 0.142374 0.4898794 0.08297800000000001 0.15628255000000002 0.27525560000000004 0.21273 0.21273 0.20597000000000001 0.2056996 0.20037155 0.0964204 0.204618 0.2070516 0.204956 0.20536160000000003 0.20029160000000001 0.20779519999999999 0.20387439999999998 0.2065108 0.20515880000000003 0.2073592 0.12348354999999998 0.08955194999999999 0.19355475000000003 0.45363709999999996 0.22125884999999998 0.678435 0.29983400000000004 0.37319435 0.528328 0.0626623 0.05148479999999999 0.1117548 0.19796 0.2109048 0.21049240000000002 0.1994732 0.14568045 0.028652699999999996 0.19421 0.16724320000000004 0.260017 0.17146584999999998 0.17665275000000003 0.193965 0.19421 0.1964717 
0.14660084999999998 0.12906835 0.08437415 0.0912355 0.22290600000000002 0.0971604 0.21676325 0.13776919999999998 0.11226715000000002 0.017239499999999998 0.1995301 0.35412170000000004 0.23077974999999998 0.47443110000000005 0.4168749 0.72500845 0.51840595 0.2327291 0.20180654999999997 0.2810191 0.24642 0.20511125 0.24523975 0.24642 0.24642 0.24642 0.16685204999999997 0.19525734999999997 0.24642 0.3238995 0.5110622499999999 0.27504735 0.47714565 0.3623935999999999 0.08104234999999999 0.21250384999999997 0.244638 0.24642 0.24642 0.24642 0.203931 0.4390119 0.39473790000000003 0.24429555 0.10329475 0.23505049999999997 0.20826144999999996 0.10411474999999999 0.27431445 0.08541069999999999 0.36178470000000007 0.13841214999999998 0.19880115 0.1351184 0.20285044999999996 0.27119309999999996 0.16169145000000001 0.1198461 0.24642 0.37924199999999997 0.2256476 0.4940878000000001 0.33148685 0.10893205 0.40843755000000004 0.39236040000000005 0.22210684999999997 0.27028625 0.31378025 0.23202095 0.32680135 0.5140145500000001 0.222815 0.5054694 0.13732724999999998 0.12234175 0.2085294 0.2298507 0.2195103 0.2256476 0.14801099999999998 0.23156999999999997 0.14490050000000002 0.0809735 0.07158540000000001 0.1382298 0.20400675 0.24287925 0.24402405 0.23225549999999998 0.17014475 0.04330385 0.21058515 0.33901875000000004 0.2545685 0.10250335 0.21212874999999998 0.226357 0.22662 0.22053080000000003 
0.15893749999999998 0.14454740000000002 0.09562414999999999 0.1028104 0.15752 0.1053068 0.23334199999999997 0.14997365000000001 0.12698084999999998 0.037634 0.21817484999999998 0.21021299999999996 0.67729235 0.6150408 0.29731725000000003 0.26126360000000004 0.2099744 0.366346 0.2058586 0.2283372 0.26253 0.208708 0.2996364 0.26253 0.26253 0.26253 0.2208814 0.4584135999999999 0.26253 0.6935345 0.514875 0.36184200000000005 0.24889755000000002 0.0928093 0.09262435 0.2211247 0.2606985 0.31587045 0.4619769 0.26253 0.42215469999999994 0.26253 0.26253 0.31460404999999997 0.11009725 0.25168775 0.22362665 0.24026564999999997 0.17289635 0.09148945 0.13333855 0.0496066 0.27676815 0.4748109999999999 0.43276544999999994 0.1037855 0.1682672 0.12927444999999999 0.26253 0.26253 0.2362522 0.56979825 0.6911239 0.12211694999999999 0.4326969500000001 0.49178599999999995 0.3937680999999999 0.3701688 0.255115 0.39554515 0.22643760000000002 0.238785 0.29043175 0.37026685 0.14676 0.13594674999999998 0.43747555 1.0214857000000002 0.35499755 0.2362522 0.15679925 0.2611824 0.19933829999999997 0.18510424999999997 0.07975375 0.15165065 0.207804 0.259364 0.2600665 0.2479532 0.18130300000000002 0.050273849999999995 0.21811680000000003 0.47131159999999994 0.2450207 0.10952524999999999 0.22962665000000002 0.24190699999999998 0.24218 0.3128297 
0.22697130000000001 0.23685685 0.16322955000000003 0.16684439999999998 0.21735655 0.11322804999999998 0.25179575 0.16351615000000003 0.1452814 0.024371450000000003 0.09353914999999999 0.13662965 0.25643875 0.528084 0.28002 0.57186 0.21537199999999998 0.2606256 0.21173555 0.23840284999999997 0.28002 0.215372 0.28002 0.28002 0.28002 0.518356 0.18710305 0.22071635 0.28002 0.28002 0.27476735 0.3698043 0.3602765 0.13736105 0.10406485 0.30492625 0.3754201 0.28002 0.28002 0.387028 0.5761336999999999 0.28002 0.28002 0.28002 0.1173038 0.2705105 0.23694795000000002 0.2144661 0.17908099999999996 0.09835394999999998 0.1476839 0.0570962 0.19382915 0.35985235000000004 0.45384 0.19001389999999996 0.36949529999999997 0.1399776 0.6180680000000001 0.28002 0.24850409999999998 0.24688790000000002 0.26789850000000004 0.12942529999999997 0.4108876 0.391856 0.34659365000000003 0.25294865 0.21537199999999998 0.25941345 0.23597854999999998 0.2517365 0.2436555 0.6009296 0.15717774999999998 0.14955175 0.22257490000000002 0.32687619999999995 0.2379988 0.24850409999999998 0.16649649999999996 0.264345 0.17313715 0.24675485000000003 0.4906644 0.17835395 0.21268975 0.27799975 0.277493 0.2650768 0.193579 0.05745609999999999 0.22706815 0.2279496 0.5665235500000001 0.11762605000000001 0.24914035 0.25883900000000004 0.25912 0.2479141

**Comment by jmschrei** [comment]
Sorry that I didn't get to this. Were you able to resolve the issue?
