### ISSUE TITLE
Multivariate (Indep. Comp. Distribution) hidden Markov model from labeled samples

### ISSUE THREAD

**Issue by charlesincharge** [jmschrei/pomegranate#689]
I also had a question similar to https://github.com/jmschrei/pomegranate/issues/501#issuecomment-564879826 . I'm not able to pass in a list of distributions to `HiddenMarkovModel.from_samples()` when using labels.

Is the suggested method to define the HMM with an `IndependentComponentDistribution` (with random initialization), then use `fit()` with samples/labels?

**To Reproduce**
```
import numpy as np
import pomegranate as pg

np.random.seed(7)
n_samples = 100
feature_dims = 15
state_names = ['0', '1']
X = np.random.rand(n_samples, feature_dims)
y = np.random.choice(state_names, size=(n_samples,))

distribution = [pg.NormalDistribution] * feature_dims # Independent normal distributions

model = pg.HiddenMarkovModel.from_samples(
    distribution, # May want to switch to IndependentComponentsDistribution
    n_components=2,
    X=[X],
    labels=[y],
    state_names=state_names,
    algorithm='labeled',
)
model.bake()
```
Output:
```
~\Anaconda3\lib\site-packages\pomegranate\hmm.pyx in pomegranate.hmm.HiddenMarkovModel.from_samples()

AttributeError: 'list' object has no attribute 'from_samples'
```
If I comment out the labels/algorithm lines for unsupervised learning, this works fine.

**Comment by jmschrei** [comment]
There are a few issues here. The first is that you just need to pass in pg.NormalDistribution instead of a list of them. The second is that after fixing that one encounters an issue related to trying to see if None is in a list that has numpy arrays. I fixed this second issue for 0.12.1. 

I've updated the documentation to mention that, when using labeled training, that each sequence of observations must begin with the start state. This means adding `None-start` to the front of each of your sequences of labels (because None is the default model name). The reason you need to include the start state label explicitly because the labels can include silent states in the model and the start state is just a silent state. Likewise, you should include the end state label if you want your model to have an explicit end state.

**Comment by charlesincharge** [comment]
Re: the first issue, @jmschrei you mentioned in https://github.com/jmschrei/pomegranate/issues/501#issuecomment-561908881 that one should pass in a list of distributions to `from_samples` to implement a `IndependentComponentDistributions`. Has that changed?

Thanks!

**Comment by charlesincharge** [comment]
(X is multi-dimensional in this case)

**Comment by jmschrei** [comment]
The change has been made on the GitHub repo that should fix this issue but I haven't released a new version because I'm waiting for a few more expected PRs to come in. Try pulling the latest code and seeing if that works for you.

**Comment by AdeLouis** [comment]
Hi @jmschrei this seems to be the last discussion on using the IndependentComponentDistribution with labelled samples when initializing the HMM. 

I am still having issues with the latest version of using this distribution. Can you give an example of how to specify the IndependentComponentDistribution when using HMM from_samples? 

I get no errors when I do this without labels by the way. The only issue is when I use labels. 

I think the error is originating from this [line](https://github.com/jmschrei/pomegranate/blob/21ffc17eab3b07ca483e65bbdaccbd267c42bbc0/pomegranate/hmm.pyx#L3611) in hmm.pyx
